mutation ($number: String!, $nationalNumber: String!, $contryCode: String) {
  mobileAuthentication(
    number: $number
    nationalNumber: $nationalNumber
    contryCode: $contryCode
  ) {
    status
    result
  }
}
