mutation (
  $username: String!
  $password: String!
  $rememberme: Boolean
  $captchaValue: String
  $captchaKey: String
  $captchaType: String
) {
  signinByUsername(
    username: $username
    password: $password
    rememberme: $rememberme
    captchaValue: $captchaValue
    captchaKey: $captchaKey
    captchaType: $captchaType
  ) {
    id
    username
    nickname
    role
    isEmailAuth
    isSnsAuth
    isPhoneAuth
    studentTerm
    status {
      userStatus
    }
    profileImage {
      id
      name
      label {
        ko
        en
        ja
        vn
      }
      filename
      imageType
      dimension {
        width
        height
      }
      trimmed {
        filename
        width
        height
      }
    }
    banned {
      username
      nickname
      reason
      bannedCount
      bannedType
      projectId
      startDate
      userReflect {
        status
        endDate
      }
    }
  }
}
